import Head from "next/head";

export interface MetaProps {
  title: string;
}

const Meta = ({ title = "NDH" }: MetaProps) => {
  return (
    <>
      <title>{title}</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </>
  );
};

export default Meta;
